# Generated by Django 4.2.2 on 2023-06-19 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vagas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_vaga', models.CharField(max_length=20)),
                ('foto', models.ImageField(upload_to='images/<django.db.models.fields.CharField>/%Y/%m/%d')),
                ('salario', models.IntegerField()),
                ('local', models.CharField(max_length=25)),
            ],
        ),
    ]
