# Generated by Django 4.2.2 on 2023-06-20 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vagas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vagas',
            name='foto',
            field=models.ImageField(upload_to='images/%Y/%m/%d'),
        ),
    ]
